### ISSUE TITLE
Questions about visualization

### ISSUE THREAD

**Issue by jiangchaokang** [KTH-RPL/DeFlow#1]
Excellent work, but when I try to use the visualization feature, I am missing a 'json' file to control the point cloud view. Could you please provide me with your av2.json file? I could use it as a reference, and if you could provide it, it would save me a lot of time. 
Thank you again for your outstanding contribution!

```python
tests/scene_flow.py

ctr = viz.get_view_control()
o3d_vctrl = ViewControl(ctr, f"{BASE_DIR}/assets/view/av2.json")

# need to set the view again, check this issue: https://github.com/isl-org/Open3D/issues/2219
o3d_vctrl.read_viewTfile(f"{BASE_DIR}/assets/view/av2.json")
 viz.update_geometry(pcd)

**Comment by Kin-Zhang** [comment]
Sure, I update the file, let me know if you have any problem to run it.
