### ISSUE TITLE
Release models on HF

### ISSUE THREAD

**Issue by NielsRogge** [KTH-RPL/DeFlow#7]
Hi @Kin-Zhang,

Niels here from the open-source team at Hugging Face. I discovered your work through the daily papers: https://huggingface.co/papers/2401.16122 (feel free to claim authorship with your HF account). I work together with [AK](https://x.com/_akhaliq) on improving the visibility of researchers' work on the hub. 

I was wondering you'd be up for collaborating on releasing the checkpoints on the 🤗 hub, I see they're currently on Sharepoint: https://github.com/KTH-RPL/DeFlow/discussions/2, to improve their discoverability. We can add tags so that people find them when filtering https://huggingface.co/models. 

## Uploading models

See here for a guide: https://huggingface.co/docs/hub/models-uploading. In case the models are custom PyTorch model, we could probably leverage the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds `from_pretrained` and `push_to_hub` to each model. Alternatively, one can leverages the [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file) one-liner to download a checkpoint from the hub. 

We encourage researchers to push each model checkpoint to a separate model repository, so that things like download stats also work. Moreover, we can then link the checkpoints to the paper page, improving their visibility.

Let me know if you're interested/need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by NielsRogge** [comment]
Thanks for letting me know! I've indexed your SeFlow paper here: https://huggingface.co/papers/2407.01702. As can be seen, no models/datasets/demos are linked to it yet. It would be great to upload those to the hub as well, to improve their discoverability. I did something similar with an optical flow paper here: https://huggingface.co/papers/2408.10161.

**Comment by Kin-Zhang** [comment]
Yes, I just finished uploaded and also update the huggingface README so it automatically linked.

Thanks for sharing!

**Comment by NielsRogge** [comment]
Great! Would be nice to update the README of the Github repos to link to the hub.

FYI there's a handy [helper function](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file) to programmatically download a file from the hub:
```python
from huggingface_hub import hf_hub_download

filepath = hf_hub_download(repo_id="kin-zhang/OpenSceneFlow", filename="deflow_best.ckpt")
```
for instance. This can be handy for quickly downloading files.

**Comment by Kin-Zhang** [comment]
Yes, doing it now. But I may not include huggingface_hub func since it may need to add another package in the environment which I tried to let people not struggle with setup an environment, I will directly use it through `wget` for example.
