### ISSUE TITLE
When I run visualization command, an error occured.

### ISSUE THREAD

**Issue by having-salt** [KTH-RPL/DeFlow#9]
I first ran:
`python save.py checkpoint=/home/qzh/DeFlow/checkpoints/deflow_best.ckpt dataset_path=/home/qzh/DeFlow/data/av2/preprocess_v2/sensor/val`
and it showed:
`We already write the flow_est into the dataset, please run following commend to visualize the flow. Copy and paste it to your terminal:
python tools/visualization.py --res_name 'deflow_best' --data_dir /home/qzh/DeFlow/data/av2/preprocess_v2/sensor/val
Enjoy! ^v^ ------ `
so I ran this command, then, an error occured.
File "tools/visualization.py", line 114, in <module>
    fire.Fire(vis)
  File "/home/qzh/anaconda3/envs/deflow/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/qzh/anaconda3/envs/deflow/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/qzh/anaconda3/envs/deflow/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "tools/visualization.py", line 73, in vis
    opt.background_color = np.asarray([80/255, 90/255, 110/255])
AttributeError: 'NoneType' object has no attribute 'background_color'

**Comment by Kin-Zhang** [comment]
Could you check your open3d version, it must >=0.18.0

**Comment by having-salt** [comment]
>>> import open3d
>>> open3d.__version__
'0.18.0'
Thanks for your reply, I have checked.

**Comment by having-salt** [comment]
but the error still exists

**Comment by Kin-Zhang** [comment]
I don’t think it’s model or data problem but open3d didn’t work on your
platform.
Could you please check in open3d repo issue if someone have same issue?
